setInterval(function(){
	$(".dish-price.dish-free").each(
		function(){
			$(this).hide();
		}
	)
	$(".dish-price.ng-binding.ng-hide").each(
		function(){
			$(this).attr('class','dish-price');
			}
	 )
},1000)
